### ISSUE TITLE
[UI/UX] prototype layout

### ISSUE THREAD

**Issue by ca333** [KomodoPlatform/atomicDEX-Pro#10]
For UI layout and UX please orientate towards these mockups: 

![dextop_wallet_view](https://user-images.githubusercontent.com/10762374/71768757-a492e680-2f19-11ea-8f13-19e93320b025.jpeg)

![dextop_DEX_dropdown01](https://user-images.githubusercontent.com/10762374/71781691-b041e400-2fd1-11ea-8c45-c6d214915d09.jpeg)

![dextop_DEX_dropdown02](https://user-images.githubusercontent.com/10762374/71768759-abb9f480-2f19-11ea-8dd8-617c0f5c4037.jpeg)

![dextop_DEX](https://user-images.githubusercontent.com/10762374/71768763-b07ea880-2f19-11ea-9df0-3e046befbe64.jpeg)

**Comment by ca333** [comment]
Font: https://fonts.google.com/specimen/Rubik?selection.family=Rubik

**Comment by ca333** [comment]
Alternative `rel` drop-down: 

![dextop_DEX_dropdown02_alternative](https://user-images.githubusercontent.com/10762374/71784273-1f2f3500-2ff2-11ea-9640-3dcdf715c3b6.jpeg)

**Comment by naezith** [comment]
Current version covers all these now.
