### ISSUE TITLE
CI builds issues

### ISSUE THREAD

**Issue by SirSevenG** [KomodoPlatform/atomicDEX-Pro#117]
List of known issues with `ci_tools_atomic_dex` automated builds.
Need to be fixed to have proper cd releases.

-- MacOS:

1. `atomicDEX-Pro.dmg` has no icon

2. debug builds do not start with debug console/log

-- Windows:

3. similarly to (2) - release builds start with cmd debug console/log

4. vcpkg does not build debug libs to provide with bundle-Debug.
a.e.: `libcurl-d.dll`, `boost-filesystem-gd-mt.dll`, etc.

-- Linux:

6. Linux builds require shared dependencies (`*.so `), currently vcpkg does not support shared libs builds. Thus, we should either build static binary or search for a workaround.

**Comment by Milerius** [comment]
@SirSevenG 

For the linux part I'm looking into https://github.com/probonopd/linuxdeployqt to see which kind of workaround we can do.

For osx:

- Icon is on your list
- Log I will look into that for osx/windows

**Comment by tonymorony** [comment]
Also app calling atomic_qt in Launchpad - should be something like "AtomicDEX-Pro"

**Comment by SirSevenG** [comment]
Linux bundling is working, yet application will not run for me. mm2 binary an entire tools folder are not included in bundle.
`./AppRun` result:
https://paste.ubuntu.com/p/DbsBXWftmt/

**Comment by tonymorony** [comment]
@SirSevenG As I can see mm2 should adding there https://github.com/SirSevenG/atomicDEX-Pro/blob/bundle_test/ci_tools_atomic_dex/src/bundle.nim#L73 do you have mm2 binary by this path? In general you can download latest mm2 from GH release page (https://github.com/KomodoPlatform/atomicDEX-API/releases) it will be even better.

Missing `tools` folder looks like a one line fix in bundling script as well if it's the case

**Comment by tonymorony** [comment]
@SirSevenG @Milerius 

FYI, Windows CD bundles doesn't work now on clean machine:

![image](https://user-images.githubusercontent.com/24797699/81521712-356b4a00-9372-11ea-85e4-a2bed87e0851.png)

![image](https://user-images.githubusercontent.com/24797699/81521821-9430c380-9372-11ea-8e16-0ab3a82a3333.png)

![image](https://user-images.githubusercontent.com/24797699/81521850-b296bf00-9372-11ea-8c44-61081e2069d4.png)

![image](https://user-images.githubusercontent.com/24797699/81521861-c04c4480-9372-11ea-91ed-a18f57e6564c.png)

**Comment by tonymorony** [comment]
CI works fine now
