### ISSUE TITLE
Add the option to see all orders

### ISSUE THREAD

**Issue by jansako** [KomodoPlatform/atomicDEX-Pro#119]
Issue: The Orders page currently does not allow to display all active orders, only per coin. 

Suggestion: Add a 'show all' or 'clear filter' option to the drop down menu:

![image](https://user-images.githubusercontent.com/34211887/80706246-d4ec2b00-8a9c-11ea-9c1e-c78b218730d5.png)

**Comment by naezith** [comment]
UI design is heavily changing, I will wait until the new design for this page is decided. Thanks for the suggestion.

**Comment by tonymorony** [comment]
Thanks for the suggestion! We've implemented that (there was a duplicate https://github.com/KomodoPlatform/atomicDEX-Pro/issues/212)

Will be availiable in 0.1.5
