### ISSUE TITLE
App dimensions work only for big screens

### ISSUE THREAD

**Issue by barbierir** [KomodoPlatform/atomicDEX-Pro#122]
Testing version v0.1.2 on Win10 on a 15" screen: lower part of the app is hidden, including buttons necessary to continue. On a 24" screen at the highest resolution it's all fine, though the buttons look small on a large surface. If the 24" screen gets scaled at 125 or 150% resolution, lower part gets hidden again. 

Attached examples: 

15"
![15_100_1](https://user-images.githubusercontent.com/35692099/80719880-650d8d00-8afc-11ea-8208-eb6fb20d9152.jpeg)

24" at highest resolution
![24_100_2](https://user-images.githubusercontent.com/35692099/80719891-69d24100-8afc-11ea-9306-a8affbdc755e.jpeg)

24" scaled at 150%
![24_150_2](https://user-images.githubusercontent.com/35692099/80719901-6e96f500-8afc-11ea-94da-20d4285bc209.jpeg)

**Comment by naezith** [comment]
Thanks for reporting, will look into this.

**Comment by barbierir** [comment]
FYI still the same for v0.1.3 in both Windows or Linux on 15" Laptop, though moving the taskbar to a side makes the 'continue' button barely clickable

**Comment by tonymorony** [comment]
> FYI still the same for v0.1.3 in both Windows or Linux on 15" Laptop, though moving the taskbar to a side makes the 'continue' button barely clickable

there will be massive UI change/improvement (layout will be totally different) so 0.1.3 patch doesn't include UI fixes

**Comment by tonymorony** [comment]
should be resolved in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/403
so will be better in 0.2.1 (already possible to try locally on one of the latest CI builds: https://github.com/KomodoPlatform/atomicDEX-Pro/actions)  :)
 thanks for that issue opening!
