### ISSUE TITLE
Rename "Cancel' to 'Cancel Order' on Order Details dialog

### ISSUE THREAD

**Issue by jansako** [KomodoPlatform/atomicDEX-Pro#127]
**Recommendation:** Rename "cancel" to "Cancel Order"

Right now both buttons "close" and "cancel" could appear to mean the same thing. 

In general, a button labelled **'Cancel'** refers to "close the dialog and return to the previous state of the application".

A **'Close'** button in general means: "I am done, close this thing with the changes I already made."

![image](https://user-images.githubusercontent.com/34211887/80795560-ad0acf00-8b51-11ea-8fc0-864995b60da6.png)

**Comment by naezith** [comment]
Thanks for the suggestion.

**Comment by tonymorony** [comment]
was changed in 0.2.0 :)
