### ISSUE TITLE
integrate contact list

### ISSUE THREAD

**Issue by coingirl87** [KomodoPlatform/atomicDEX-Pro#128]
Hi, is it possible to integrate an contact list to send function?

![image](https://user-images.githubusercontent.com/64635975/80795620-3f849000-8b9d-11ea-944e-345758b1388b.png)

Thank you

**Comment by Milerius** [comment]
I'm not against it @naezith, i can add it with the wallet name in a specific file: `wallet_name.contact_list`

**Comment by naezith** [comment]
> I'm not against it @naezith, i can add it with the wallet name in a specific file: `wallet_name.contact_list` but since the UI is changing a lot i would prefer wait for the new UI to implement this feature

This would be a design decision @ca333 would need to make.

**Comment by tonymorony** [comment]
Thanks for the issue opening!
 Implemented in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/357
