### ISSUE TITLE
integrate copy function

### ISSUE THREAD

**Issue by coingirl87** [KomodoPlatform/atomicDEX-Pro#129]
Hi, is it possible to integrate an copy function? For example i try to copy the swap id but its not possible. Thank you

**Comment by naezith** [comment]
Thanks for the suggestion.

**Comment by naezith** [comment]
https://github.com/KomodoPlatform/atomicDEX-Pro/commit/4f2bb8c52b1ce9d98bd7c22d86af90627077492a
https://github.com/KomodoPlatform/atomicDEX-Pro/commit/4d4320305a2c9eaf9873dd36a396d8e4659ae6ab

**Comment by tonymorony** [comment]
thanks for issue opening! you should be able to copy text by Ctrl+C now

**Comment by damascene** [comment]
I'm not able to copy the swap ID in version: 2.1.4027_mm2.1-slp-swap_2aae2b680_Linux_Release
