### ISSUE TITLE
Show full balance in fiat in the GUI

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Pro#13]
Property: `Q_PROPERTY(QString balance_fiat_all READ get_balance_fiat_all WRITE set_current_balance_fiat_all NOTIFY on_fiat_balance_all_changed)`

Close with commit url when it's done !

**Comment by naezith** [comment]
https://github.com/KomodoPlatform/atomicDEX-Pro/commit/a5c2058519c15d4bdf483841edf09203f7966c84
