### ISSUE TITLE
Swaps stucks at 2/3 Swap ongoing

### ISSUE THREAD

**Issue by coingirl87** [KomodoPlatform/atomicDEX-Pro#130]
Hi,

all my swaps stucks at 2/3 Swap ongoing.

![image](https://user-images.githubusercontent.com/64635975/80796532-bcb10480-8b9f-11ea-890e-eee92991c02b.png)

Thank you

**Comment by Milerius** [comment]
Let us know if the swaps timed out after 30minute, state should change, if it's the case you can retrieve the logs file and share it here. (Settings, open logs folder)

**Comment by coingirl87** [comment]
Hi, 
issue can be closed...the swaps are all successful after a while..it depends to the confrmations right? if yes, it would be helpful if there is another information like 10 of 12 confirmations are done or estimated time 10 minutes. I can open another issue for that?

Thank you

**Comment by Milerius** [comment]
@coingirl87 Hello, it's probably related to https://discordapp.com/channels/412898016371015680/584762059430821909/705532140741460038

Coins config is waiting for 2 notarizations now which can take a some time.
