### ISSUE TITLE
Allow Export of Swap History (Recent Swaps)

### ISSUE THREAD

**Issue by jansako** [KomodoPlatform/atomicDEX-Pro#135]
**Issue:**  It is currently not possible to export the 'recent swaps' list for the UI.

**Use case:** Analytics, evaluation of trade strategies, bots, backtesting, to support importing into accounting software and/or paying taxes on trades, as unpopular as they maybe.

**Suggestion:** Allow export to CSV and XLSX formats. 
**Nice to have:** If a filter is introduced, the export should respect the filtered list (e.g export only successful swaps).

**Comment by Milerius** [comment]
It's very easy to implement for the full export.

For the filter export you will need to wait a bit more.

I'm on the full export right now.

**Comment by naezith** [comment]
Another feature to consider at UI design @ca333

**Comment by Milerius** [comment]
Already approved by @ca333. However this is a minor improvements, and can be implemented after the major UI update, backend is already ready with #137. Will probably need some tweaks in the future !

I let the issue open for future discussion.

**Comment by tonymorony** [comment]
CSV export of trading history implemented in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/476
will be available in 0.3.0 release
