### ISSUE TITLE
Spinning for ETH/ERC-20 coins loading

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Pro#14]
I will add in the backend a `current_coin_info.state` that can be `InProgress` or `Finished`

If it's `InProgress` we need to show in the UI a Spinning Circle  + the message `Loading Syncing ` + `current_coin_info.current_block TXs`

State and Current block are not yet available

The transactions arrive little by little during synchronization, we display the spinning loading + the transactions step by step when state goes to `Finished`, we remove the spinning effect and the message

**Comment by naezith** [comment]
I put this to the transactions list position, I can change if it's wanted as non-closable blocking modal.

https://github.com/KomodoPlatform/atomicDEX-Pro/commit/8070997df39a999a1274da4d5eb192d5b1423b2b
