### ISSUE TITLE
Trade Screen - Resets Sell Amount to Max after selecting from Orderbook

### ISSUE THREAD

**Issue by crackityj** [KomodoPlatform/atomicDEX-Pro#140]
In Trade Screen

- Select Sell Coin and update balance to something less than Max
- Open Receive Coin Orderbook
- Select swap from order book
- When you go back to the Trade Screen the Sell Amount has reset to Max

**Comment by naezith** [comment]
Thank you for reporting, I'll look into this.

**Comment by jansako** [comment]
I think the behavior **when selecting an existing order** should be to pre-fill the 'sell' side of the new order creation to:
- fill the whole order 
- if balance is not sufficient, then use the own balance

When choosing to **create own order**, the values pre-filled in the 'sell' box before should be remembered.

I think the related issue here could be that we are not able to change the receive coin without going into the orderbook.

**Comment by tonymorony** [comment]
This one should be resolved by #143
