### ISSUE TITLE
Sell Dash - Max Amount - Missing Error Handling

### ISSUE THREAD

**Issue by crackityj** [KomodoPlatform/atomicDEX-Pro#141]
Trade Screen

- Select Dash - Max balance 
- Select KMD to receive
- Confirm Swap

Swap never shows up as active

Suspect this is the same Max value for Dash issue that is in Mobile version but with no error handling to let user know it failed.

Was able to get a successful Dash > KMD swap when I reduced the Dash amount slightly.

**Comment by cipig** [comment]
same as #96

**Comment by tonymorony** [comment]
closed as duplicate, there is some progress in #96
