### ISSUE TITLE
dll missing for Windows 10

### ISSUE THREAD

**Issue by barbierir** [KomodoPlatform/atomicDEX-Pro#165]
Installing 0.1.3 on a fresh Windows 10 (in Virtualbox), AtomicDex asks for missing msvcp140.dll & vcruntime140_1.dll

**Comment by Milerius** [comment]
Hello @barbierir can you tell me it's the version downloaded with the installer or it's the bundle  ?

**Comment by Milerius** [comment]
<img width="626" alt="Capture d’écran 2020-05-18 à 18 26 37" src="https://user-images.githubusercontent.com/21139416/82236936-287fc500-9935-11ea-8f25-c49845165a6b.png">
Seems to be present in the bundled version

**Comment by Milerius** [comment]
<img width="1680" alt="Capture d’écran 2020-05-18 à 18 28 28" src="https://user-images.githubusercontent.com/21139416/82237089-6846ac80-9935-11ea-9046-21b3077e1207.png">
The version installed with the installer seems to run on a new machine too

**Comment by Milerius** [comment]
<img width="1148" alt="Capture d’écran 2020-05-18 à 18 30 30" src="https://user-images.githubusercontent.com/21139416/82237279-ae9c0b80-9935-11ea-8237-87eb43ab098e.png">
And the dll are also present here

**Comment by tonymorony** [comment]
@Milerius I've also just re-cheked all 3 bundles and all dlls are on place

**Comment by barbierir** [comment]
Yeah it's strange, I used "atomicdex-pro-0.1.3-alpha-windows-installer.exe" and I didn't had a similar message when I tried 0.1.2

I'll do another fresh windows 10 install and try again, I'll let you know tomorrow

**Comment by barbierir** [comment]
Ok tried on a fresh Win10 install and also on wife's computer Win10 and in neither case I was asked for those dll. So it's all fine now, I can't reproduce the issue.
