### ISSUE TITLE
[Claiming rewards]: Backend Frontend

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Pro#17]
To be able to recover the rewards of a coin we need several notions:

Is my currency a currency on which the rewards exist `(coin_info.is_claimable == true)`

Does my currency allow the recovery of the rewards and has the minimum amount to claim the reward `(coin_info.is_claimable && balance(current_coin) > coin_info.minimal_claim_amount)`

Does my currency allow the recovery of the rewards and has the minimum amount to claim the reward  and i didn't claim it since one hours `(coin_info.is_claimable && balance(current_coin) > coin_info.minimal_claim_amount && is_claiming_ready(current_coin.ticker))`

C++ function will be exposed when ready

**Comment by Milerius** [comment]
```cpp
Q_INVOKABLE bool     is_claiming_ready(const QString& ticker);
Q_INVOKABLE QObject* claim_rewards(const QString& ticker);
```

**Comment by Milerius** [comment]
You also have inside the current coin info and enabled_coin list the minimal_claimable_amount, if your balance is under the minimal amount, you cannot claim.

**Comment by naezith** [comment]
Implementation is complete, needs test.
