### ISSUE TITLE
Ethereum synching

### ISSUE THREAD

**Issue by barbierir** [KomodoPlatform/atomicDEX-Pro#173]
Both Win and Linux versions. When activating Ethereum there's a spinning loading wheel in its page. I see from etherscan that it started at the most recent block and the count increases keeping up with new ethereum blocks. I left it running for one hour with no change. Is that expected behaviour? I previously noticed the same with atomicdex mobile on android. 

![Schermata del 2020-05-20 18-40-27](https://user-images.githubusercontent.com/35692099/82475311-96122980-9acc-11ea-8db9-fa11e63749c4.png)

**Comment by artemii235** [comment]
Transactions history response from atomic-DEX format is different for UTXO and ETH coins: https://developers.komodoplatform.com/basic-docs/atomicdex/atomicdex-api.html#my-tx-history. For UTXO there's `transactions_left`, but for ETH/ERC20 it is `blocks_left`. Seems like GUIs display `blocks_left` as transactions count which is wrong.

**Comment by Milerius** [comment]
Yeah @artemii235 

@naezith it's possible to switch the text so it's make more sense ?

**Comment by Milerius** [comment]
@artemii235 We don't print `transactions_left` or `blocks_left` but `current_block` actually.

We will update the text for 0.1.4

**Comment by naezith** [comment]
https://github.com/KomodoPlatform/atomicDEX-Pro/pull/174

**Comment by Milerius** [comment]
solved #175
