### ISSUE TITLE
Base max amount on trade moving not inside selected order capacity

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#178]
Problem:  when you select order to fill in orderbook it shouldn't be possible to select base coin amount more than selected order max. amount

For example I select order in orderbook with max amount 1 DEX:

![image](https://user-images.githubusercontent.com/24797699/82572909-448e9b00-9baf-11ea-8f44-2ed6f12db90f.png)

But after selection for KMD amount selected max. and for DEX amount of my KMD multiplied on rate of the order I've selected:
 
![image](https://user-images.githubusercontent.com/24797699/82573162-9fc08d80-9baf-11ea-9150-07239a9b3ec8.png)

You can try to select order in mobile orderbook and issue might became more clear than my explanation. Keep in mind that in DEX we fill concrete order.

**Comment by naezith** [comment]
I am doing the change directly to the new UI since this feature has so much UI code. 

One part I am not sure about is will setting base as `Maximum Rel Volume / Price` be enough? That's what mobile application does.

**Comment by naezith** [comment]
New UI design goes with traditional way where order is partially matched and rest of it becomes maker order. Discarded the changes I did for now.

**Comment by naezith** [comment]
`10 MORTY <-> 15 RICK` at mobile 
then 
`30 RICK <-> 20 MORTY` at PC, they do not match. PC one becomes maker as well.

Both are priced `1 MORTY = 1.5 RICK`.

This is the case this issue tries to handle I think.

**Comment by cipig** [comment]
This failed swap might be related to this issue:
https://dexapi.cipig.net/public/error.php?uuid=1de2d3de-6ada-41aa-9ced-c8c998e7d6ac

**Comment by naezith** [comment]
Capped both orderbook receive values and base input, at the new UI. Currently at `naezith_dev` branch. It works same as mobile now.

**Comment by Milerius** [comment]
Can we have it in the old ui too ?

**Comment by naezith** [comment]
> Can we have it in the old ui too ?

We better not to, this view will change a lot. It would be waste of time.

**Comment by tonymorony** [comment]
Should improve UI in 0.1.5, thank you for implemeting that
