### ISSUE TITLE
Systematic/global order matching rounding issue

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#179]
https://paste.ubuntu.com/p/tNj6PnQGHB/ if to check orderbook as DEX-KMD initial price is in integers

https://paste.ubuntu.com/p/vm2g6kCqdV/ if to check KMD-DEX it's 0.06666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666667
 
If to check in GUI it's 0.06666667 what is not actual price (actual is `0.06666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666667` as you can see):

![image](https://user-images.githubusercontent.com/24797699/82575025-1eb6c580-9bb2-11ea-8e03-5592ba336c3c.png)

Actual price is 1 DEX - 15 KMD as you can see from DEX-KMD
But now if I select the order and input 15 KMD it's not 1 DEX but 1.00000005

![image](https://user-images.githubusercontent.com/24797699/82575736-0dba8400-9bb3-11ea-9680-55f0dc91d02d.png)

![image](https://user-images.githubusercontent.com/24797699/82575830-2c207f80-9bb3-11ea-88b3-6d190621036b.png)

As a result I never match order (because my price is different from actual 15 KMD : 1 DEX one) but placing own instead:

![image](https://user-images.githubusercontent.com/24797699/82575939-52deb600-9bb3-11ea-8ab0-f46a0e8eb9af.png)

**Comment by Milerius** [comment]
solved #180
