### ISSUE TITLE
"unconfirmed" state not changing for all received transactions until app restart

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#197]
~~To reproduce open the app, receive some transaction and then track it's confirmation status in explorer/mm2 response and in GUI~~

UPD: maybe I've miss-interpret the issue a little bit - looks like only taker payment I've sent in swap and maker payment I've received stuck in such state but fees displayed fine. Will do better research with mm2 outputs comparison and share results.

UPD2: caused by such mm2 behaviour https://github.com/KomodoPlatform/atomicDEX-API/issues/652 it seems

![image](https://user-images.githubusercontent.com/24797699/83301627-29153700-a224-11ea-9bf5-7b84194a68b0.png)
![image](https://user-images.githubusercontent.com/24797699/83301642-329e9f00-a224-11ea-8020-51dda004e071.png)
![image](https://user-images.githubusercontent.com/24797699/83301828-7f827580-a224-11ea-9613-f1f37c4a610d.png)

https://kmdexplorer.io/tx/ef1c4f112a45791ac315c5e8e5e76a4e5aa44d195f828aae1d5cdb0f9b0d8436

**Comment by naezith** [comment]
Let me know if this requires a front-end change.

**Comment by tonymorony** [comment]
the issue was fixed on api side: https://github.com/KomodoPlatform/atomicDEX-API/issues/652
to fix it on GUI side (and close this issue) mm2 version needs to be bumped

**Comment by tonymorony** [comment]
this one was fixed
