### ISSUE TITLE
[todo] num datatype

### ISSUE THREAD

**Issue by ca333** [KomodoPlatform/atomicDEX-Pro#2]
https://github.com/KomodoPlatform/atomicDEX-QT/blob/f6f35bd9663ddb26c615f4c69cfb56fd75746c5d/src/atomic.dex.gui.cpp#L47-L66

fyi - for the production version we will use rational datatype (in the "backend") when it comes to order-handling since the logic there does require divisions/multiplications at some point - for API fetched data like balance and TX amounts we will be using fixed-point arithmetic to calculate USD value, etc. thus storing these amounts in integer representations (cents/pennies) - for arithmetic operations on and representations of decimal nums we will use one of the arbitrary-precision arithmetic libraries like gmp, mpfr, etc. 

relevant infos:
https://bitcointalk.org/index.php?topic=13837.0
https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency

https://ieeexplore.ieee.org/document/8766229
https://gmplib.org/
https://www.mpfr.org/
https://en.wikipedia.org/wiki/List_of_arbitrary-precision_arithmetic_software
https://en.wikipedia.org/wiki/List_of_C%2B%2B_multiple_precision_arithmetic_libraries

https://github.com/KomodoPlatform/atomicDEX-QT/commit/f6f35bd9663ddb26c615f4c69cfb56fd75746c5d#r36293782

**Comment by Milerius** [comment]
https://www.boost.org/doc/libs/1_71_0/libs/multiprecision/doc/html/index.html

Seem's really interesting, and I will not be against using boost libraries in this project.

**Comment by Milerius** [comment]
For the rational there is: https://www.boost.org/doc/libs/1_71_0/libs/multiprecision/doc/html/boost_multiprecision/tut/rational/gmp_rational.html

**Comment by Milerius** [comment]
To be sure.

We need to do all the operation using: 

https://developers.komodoplatform.com/basic-docs/atomicdex/atomicdex-api.html#note-about-rational-number-type

Instead of the string representation alright ?

**Comment by ca333** [comment]
> To be sure.
> 
> We need to do all the operation using:
> 
> https://developers.komodoplatform.com/basic-docs/atomicdex/atomicdex-api.html#note-about-rational-number-type
> 
> Instead of the string representation alright ?

yes

**Comment by Milerius** [comment]
Done by using boost.multiprecision
