### ISSUE TITLE
Settings and activated coins are global

### ISSUE THREAD

**Issue by dathbezumniy** [KomodoPlatform/atomicDEX-Pro#209]
Settings and coins should be Isolated to a wallet where they are assigned.

Let's say I'm using wallet A (restored from seed in my case) with activated coins A1, B1, C1, ... Z1
Then I'm creating new wallet B (or restore it from another seed) - and I'm expecting to see default coins there - but I see the same coins as were activated in wallet A.
But I never wanted to use these coins in wallet B so have to deactivate it one by one.

[ https://github.com/ca333/komodoDEX/issues/789#issuecomment-636787759 ]

**Comment by Milerius** [comment]
I will target this for 0.1.5, require lot of change

**Comment by tonymorony** [comment]
Implemented, will presist in 0.1.5 release. Thanks!
