### ISSUE TITLE
"ALL" option in Orders  [Feature Request]

### ISSUE THREAD

**Issue by lilszi** [KomodoPlatform/atomicDEX-Pro#212]
Can we get an option to see ALL orders on the orders tab not just a selected coin's active orders?

**Comment by tonymorony** [comment]
Thank you for the issue openining! That something what will be considered during UI layout rewamp

**Comment by tonymorony** [comment]
Will improve UI in 0.1.5, thank you for implemeting that and thanks for proposal :)
