### ISSUE TITLE
Maker order always displays initial base coin amount

### ISSUE THREAD

**Issue by SirSevenG** [KomodoPlatform/atomicDEX-Pro#213]
After partial filling, maker orders still display initial base coin amount in orders tab.
Users have no reliable method to check remaining coins to be swapped in app.

Mobile issue: https://github.com/ca333/komodoDEX/issues/791
Related API issue: https://github.com/KomodoPlatform/atomicDEX-API/issues/486

**Comment by tonymorony** [comment]
Closing this one because its on the api side
