### ISSUE TITLE
Issues with maker orders display in history tab

### ISSUE THREAD

**Issue by SirSevenG** [KomodoPlatform/atomicDEX-Pro#215]
1. Maker orders in history are marked as `Taker Order`.
(see example below)

2. Taker and maker payment txes are not displayed in maker order.

As example. Single order, taker node:
![Taker_node](https://user-images.githubusercontent.com/44422309/83652548-f59c2900-a5e4-11ea-9730-8e586661aef5.PNG)

Maker node:
![Maker_node](https://user-images.githubusercontent.com/44422309/83652609-03ea4500-a5e5-11ea-893f-c3744823b079.PNG)

**Comment by SirSevenG** [comment]
similar issue on mobile UI:
https://github.com/ca333/komodoDEX/issues/793

**Comment by naezith** [comment]
Are you sure this is not the backend values being incorrect? @Milerius

**Comment by naezith** [comment]
That is basic as `item.am_i_maker ? qsTr("Maker Order") : qsTr("Taker Order"))`

**Comment by naezith** [comment]
And the `Taker Payment ID` and `Maker Payment ID` are searched like this:

```js
    function getSwapPaymentID(swap, is_taker) {
        if(swap.events !== undefined) {
            const search_name = is_taker ? "TakerPaymentSent" : "MakerPaymentSpent"
            for(const e of swap.events) {
               if(e.state === search_name) {
                   return e.data.tx_hash
               }
            }
        }

        return ''
    }
```

**Comment by SirSevenG** [comment]
Looks fine now on build:
https://github.com/KomodoPlatform/atomicDEX-Pro/runs/739710878

Thanks.

**Comment by SirSevenG** [comment]
Fixed by https://github.com/KomodoPlatform/atomicDEX-Pro/pull/219
Currently in dev branch.
