### ISSUE TITLE
Time a bit off on txs with explorer's time

### ISSUE THREAD

**Issue by dathbezumniy** [KomodoPlatform/atomicDEX-Pro#225]
Noticed some timeshift on txs between pro and explorer(not sure maybe it's their server time that is a bit off).
<img width="141" alt="Screenshot 2020-06-06 at 00 54 03" src="https://user-images.githubusercontent.com/11756768/83975293-d0b4f800-a8fb-11ea-9408-08a8213aca6d.png">
<img width="573" alt="Screenshot 2020-06-06 at 00 53 53" src="https://user-images.githubusercontent.com/11756768/83975296-d3afe880-a8fb-11ea-8353-ace22995178c.png">

**Comment by tonymorony** [comment]
Actually there is no shift - just explorer converting timezone to your local one.
It might be worth to show time in local time or at least add "UTC" in the end so for user it'll be clear that it's UTC

**Comment by Milerius** [comment]
Maybe worth to ask @HowardHinnant from https://github.com/HowardHinnant/date if it's possible to change the timezone conversion from UTC to local time zone of the computer

**Comment by Milerius** [comment]
There is: https://howardhinnant.github.io/date/tz.html i think it's worth to check

**Comment by tonymorony** [comment]
https://doc.qt.io/qt-5/qdatetime.html#details with  QTimeZone class to get timezone
@Milerius  you already have a timestamp from Atomicdex-API
technically converting timestamp to another timezone is sum of one integer (timestamp in UTC in our case) with another (diff with UTC)
is it difficult to calculate sum in C++ ?

**Comment by Milerius** [comment]
Time zone is much more complicated than that that's why we use wrapper for that there is lot of little trick

**Comment by Milerius** [comment]
I think I'll will use to library which is already used in the project

**Comment by Milerius** [comment]
fixed by #237

**Comment by tonymorony** [comment]
Timezones functionality was implemented, will persists in 0.1.5 so user will see dates in his local times
