### ISSUE TITLE
Crashes on DEX page

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#229]
App closing happens when app works in background for some time, never caught it right after start.
It seems that something bad happening when orderbook calling very intensive 

My log from Windows:
https://paste.ubuntu.com/p/YTR2DdsGSZ/

Users log from OSX:
[2020-06-07-17-39-51 (1).log](https://github.com/KomodoPlatform/atomicDEX-Pro/files/4748320/2020-06-07-17-39-51.1.log)

My trace from OSX:
https://paste.ubuntu.com/p/RT26p6Vdy9/

Last catch on Windows:

![image](https://user-images.githubusercontent.com/24797699/84272834-24238200-ab58-11ea-8094-6f54018f9d31.png)

**Comment by Milerius** [comment]
@tonymorony Under testing with the new log system, should solved this issue.

**Comment by tonymorony** [comment]
Tested whole week,and provided to few testers who use app quite often - looks like that problem totally resolved so should be fine in 0.1.5
