### ISSUE TITLE
Minimum trade amount

### ISSUE THREAD

**Issue by naezith** [KomodoPlatform/atomicDEX-Pro#23]
![image](https://user-images.githubusercontent.com/6732486/77258024-f29dc780-6c88-11ea-866d-f0a130e1320a.png)

We lack this warning. Mobile app clears the input box and puts that error if your amount is too low. Perhaps we need a `min_trade_amount` from backend?

**Comment by tonymorony** [comment]
In general this issue looks like an individual case of https://github.com/KomodoPlatform/atomicDEX-Pro/issues/226 because API return error if you trying to start trade with one of the amounts less than 0.00777. And at the moment GUI blocking button. So closing that in favour of #226
