### ISSUE TITLE
Recent Swaps is empty, ongoing swaps are not visible in Orders

### ISSUE THREAD

**Issue by lilszi** [KomodoPlatform/atomicDEX-Pro#234]
Recent Swaps (History) tab is empty although I had many orders completed. 
The JSON files are in their place, I can find the orders manually. 

When I initiate a new swap, on the Orders tab it appears for a second, then disappears and never to be seen again. 

Windows 10 1909
AtomicDEX Pro  0.1.4.a release

**Comment by tonymorony** [comment]
@Milerius "StartFailed" event's swaps breaking that:

example of such jsons:

https://paste.ubuntu.com/p/q39zYMQ5VP/
https://paste.ubuntu.com/p/q9hjfdbDBw/

tyvm @lilszi for help

**Comment by Milerius** [comment]
#244 should solve this, need to be confirmed !

**Comment by lilszi** [comment]
it's solved. 
"StartFailed" event doesn't have result key, glitching the GUI

**Comment by tonymorony** [comment]
tyvm for help with investigation @lilszi ! and tyvm for fix :) 
should be fine in 0.1.5
