### ISSUE TITLE
Update QT version to 5.15.0

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#235]

**Comment by tonymorony** [comment]
tested locally - it works smooth, have to update CI now to produce actual artefacts

**Comment by Milerius** [comment]
Just apart from the fact that @naezith  has reported some UI problems with the new version of QT (He fixed everything already), all of them seem stable now on this last version and even fix some bug that we had previously.

**Comment by tonymorony** [comment]
Yeah, looks like transition was smooth and helped to solve few problems such as random QT crashes and crashes on Tab button usage
