### ISSUE TITLE
Handling RPC Error Responses

### ISSUE THREAD

**Issue by naezith** [KomodoPlatform/atomicDEX-Pro#24]
![image](https://user-images.githubusercontent.com/6732486/77258071-4ad4c980-6c89-11ea-830b-77833406eb6b.png)

Even if RPC returns an error,

`22 13:56:49, rpc:305] RPC error response: rpc:274] lp_coins:536] utxo:1391] utxo:654] Output value 0 is less than dust amount 1000`

API returns `"has_error":false,"error_message":""`

This one is just a test with 0 amount send, which won't be allowed by front-end anyways. 

But for all API calls we need to make sure they check the RPC error responses and return them.

**Comment by tonymorony** [comment]
ouch sorry, we've made dupl for this one (https://github.com/KomodoPlatform/atomicDEX-Pro/issues/226)
