### ISSUE TITLE
display error in "Swap Details"

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Pro#246]
![image](https://user-images.githubusercontent.com/32116761/84511466-1257f100-acb6-11ea-9b1f-f48d59f1fc36.png)

- "Maker Payment ID" is actually the txid of "Taker Payment"
- "Taker Payment ID" is actually the txid of "Maker Payment Spent"
- the link to erc20 blockexplorer does not work because txids on etherscan start with `0x`
https://etherscan.io/tx/0x75dba66003f0852d61f3700f26b231ad25dad4c3db8960c4405f8ca2cc01377f

**Comment by naezith** [comment]
@cipig I'll rename them more precisely then.

Please confirm: 

- Maker Order will have:
  - Maker Payment Sent ID
  - Taker Payment Spent ID
- Taker Order will have:
  - Maker Payment Spent ID
  - Taker Payment Sent ID

**Comment by cipig** [comment]
confirmed :-)

**Comment by cipig** [comment]
fixed, thanks
