### ISSUE TITLE
Default fee of withdraw (get_trade_fee)

### ISSUE THREAD

**Issue by naezith** [KomodoPlatform/atomicDEX-Pro#26]
It would be great to disable the send button if user can't even pay the withdraw fees.

Here is how to have it by providing only the ticker:

```
curl -s --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"get_trade_fee\",\"coin\":\"ETH\"}" | json_pp
{
   "result" : {
      "coin" : "ETH",
      "amount" : "0.0009"
   }
}
```

**Comment by tonymorony** [comment]
Is it still actual problem?

**Comment by naezith** [comment]
I just checked the send code. To block the send button, `do_i_have_enough_funds` is used but I think that just compares the amount with balance. If custom fees is selected, then it calculates fees and checks that but if not, then there is no check for the fees or minimum send amount.
