### ISSUE TITLE
Ceiling precision of max_taker_vol for 8 digit input comparisons

### ISSUE THREAD

**Issue by naezith** [KomodoPlatform/atomicDEX-Pro#271]
This is necessary to avoid future bugs which are random and incredibly hard to debug, where orders do not match for example.

https://github.com/KomodoPlatform/atomicDEX-API/pull/671 adds `max_taker_vol` and it has only `denom` and `nomer`. 

UI allows users to enter up to 8 decimal points like `0.12345678`. User input will be capped with `max_taker_vol` so we need to create a precise float number from `denom` and `nomer`.

If input is `>= max`, sell function will be called withd `max_taker_vol`'s `denom` and `nomer`, otherwise it will be called with the user input directly.

Let's say `nomer / denom = 0.123456780001`, and user input is `0.12345678`. Normally user input is safe, not max, because `0.12345678 < 0.123456780001`. However Javascript is having issues over 8 decimals. It converts `0.123456780001` to `0.12345678` automatically. `0.12345678 == 0.12345678` so it will falsely say that it's max. But if that long value ceils to `0.12345679`, it will compare `0.12345678 <  0.12345679` and say that it is not max, which is correct.

That's why I need a separate value, `volume`, among with `denom` and `nomer`. This volume has to be:

- Maximum of 8 digits
- Extra part should ceil and add to last digit

For example:
`{ nomer: "123456780001", denom: "1000000000000", volume: "0.12345679"`. Notice that volume has maximum of 8 decimal points, and it's did `CEIL` instead of `ROUND`. 

`123456780001 / 1000000000000 = 0.123456780001`, extra part is `0001` which is `> 0` so it adds `0.0000001 (8 digits)` making the final value `0.12345679`. A normal std function which limits the digits would do this by rounding, that would result as `0.12345678` which is problematic as I explained above.

I prepared a function at Javascript, it works perfectly with strings but the double calculation is still very limited so it's useless at Javascript side. Boost's precision calculation would solve this.

 @Milerius You can port my code to `boost` and test:

 ```js
const amountPrecision = 8

// Always ceils up after precision, eg. 0.123456780001 becomes 0.12345679, rounding could produce 0.12345678 instead
function formatDouble(v, precision) {
  if(precision === undefined) precision = amountPrecision

  const decimal_index = v.indexOf(".")
  if(precision === 0 || decimal_index === -1) return parseInt(v).toString()
  
  const after_precision = v.substr(decimal_index + amountPrecision + 1) // This is the extra part, like 0001 for 0.123456780001
  
  // If it's already a short string, or if it's already <= max digits without the trailing zeros, just return
  if(after_precision === "" || parseInt(after_precision) === 0) return parseFloat(v).toString()
  
  // Otherwise ceil the last digit
  // Add 0.0000001 to the max digits value
  const max_digits_value = parseFloat(v.substr(0, decimal_index + amountPrecision + 1)) // This is the limited part, like 0.12345678 for 0.123456780001
  const addition = Math.pow(10, -amountPrecision) // This is the ceiling addition, like 0.00000001
  const final = max_digits_value + addition // This is the final value, like 0.12345679

  // Make it max digits again, then remove trailing zeros
  return final.toFixed(precision || amountPrecision).replace(/\.?0+$/,"")
}
```

And then test like this:

```js
function test(value, expected) {
  const result = formatDouble(value)
  console.log("value: " + value + "\tresult: " + result + "\texpected: ", expected, "\t- ", result === expected ? "success" : "fail")
}

test("12345678","12345678")
test("12345678.","12345678")
test(".1","0.1")
test("12345678.123456","12345678.123456")
test("12345678.1234560","12345678.123456")
test("12345678.12340001","12345678.12340001")
test("12345678.123400011","12345678.12340002")
test("12345678.123450000001","12345678.12345001")
test("12345678.12345670000001","12345678.12345671")
test("12345678.12345670000000","12345678.1234567")
test("12345678.12345678000000","12345678.12345678")
test("12345678.12345678000001","12345678.12345679")
test("12345678.12345670001","12345678.12345671")
test("12345678.12345678001","12345678.12345679")
test("12345678.123456787","12345678.12345679")
test("12345678.12345678777777","12345678.12345679")
test("12345678.12345678499999","12345678.12345679")
test("12345678.123456782","12345678.12345679")
test("12345678.12345678222222","12345678.12345679")
test("12345678.12345678199999","12345678.12345679")
test("12345678.123456785","12345678.12345679")
test("12345678.123456789","12345678.12345679")
test("12345678.123456799","12345678.1234568")
```

Output should be like this:

```js
value: 12345678    result: 12345678    expected: 12345678    - success
value: 12345678.    result: 12345678    expected: 12345678    - success
value: .1    result: 0.1    expected: 0.1    - success
value: 12345678.123456    result: 12345678.123456    expected: 12345678.123456    - success
value: 12345678.1234560    result: 12345678.123456    expected: 12345678.123456    - success
value: 12345678.12340001    result: 12345678.12340001    expected: 12345678.12340001    - success
value: 12345678.123400011    result: 12345678.12340002    expected: 12345678.12340002    - success
value: 12345678.123450000001    result: 12345678.12345001    expected: 12345678.12345001    - success
value: 12345678.12345670000001    result: 12345678.12345671    expected: 12345678.12345671    - success
value: 12345678.12345670000000    result: 12345678.1234567    expected: 12345678.1234567    - success
value: 12345678.12345678000000    result: 12345678.12345678    expected: 12345678.12345678    - success
value: 12345678.12345678000001    result: 12345678.12345679    expected: 12345678.12345679    - success
value: 12345678.12345670001    result: 12345678.12345671    expected: 12345678.12345671    - success
value: 12345678.12345678001    result: 12345678.12345679    expected: 12345678.12345679    - success
value: 12345678.123456787    result: 12345678.12345679    expected: 12345678.12345679    - success
```

**Comment by artemii235** [comment]
> If input is >= max, sell function will be called withd max_taker_vol's denom and nomer, otherwise it will be called with the user input directly.

I see some "danger" in this, if `user input > max` GUI should not allow to create such order at all. Magically setting the volume to lower amount may create incorrect users expectations because trade will be a bit different in fact.

What if we make input *inactive* if max button is clicked and display the decimal representation of expected trade volume to user not allowing to apply any changes to it? Btw I can add more information to `max_taker_vol` for such purpose returning the coin specific decimal representation of `volume` and `dex fee` because in the end it will be cut to coin decimals anyway.
But you will have to deal with more than 8 decimals for example for ETH and most of ERC20 tokens.

**Comment by naezith** [comment]
> I see some "danger" in this, if `user input > max` GUI should not allow to create such order at all. Magically setting the volume to lower amount may create incorrect users expectations because trade will be a bit different in fact.

When `user input > max` is detected, `user input = max` set will be done, then when in the moment when user confirms the trade, `user input == max` check will return true, and instead of that float representation of the max, `denom` and `nomer` will be sent to the `send` call. Isn't this safe?

> What if we make input _inactive_ if max button is clicked and display the decimal representation of expected trade volume to user not allowing to apply any changes to it? 

There isn't a max button. Also it's not the only case where input is set to max. Mobile application is also working the same. Let's say you have `4.777` balance, if you enter `5`, it automatically makes that `4.777` minus fees etc. 

> Btw I can add more information to `max_taker_vol` for such purpose returning the coin specific decimal representation of `volume` and `dex fee` because in the end it will be cut to coin decimals anyway. But you will have to deal with more than 8 decimals for example for ETH and most of ERC20 tokens still. E.g. `1/3` of ETH will turn into `0.333333333333333333`.

Yes, that's what I need, either from you or Slyris. 8 decimals max. Just like I explained above, for 3333333333 value, we need to cut 8 decimals first, so it's `0.33333333`, then if the remaining `33333` or `0001` or `111` or `0223` whatever it is, if that part is `> 0` then we need to increment the 8th digit by 1 by adding `0.00000001`. `0.33333333` will become `0.33333334`. That ceiled value will make all comparisons act correctly as I explained at first post. The calculation function is also there.

**Comment by artemii235** [comment]
> There isn't a max button.

I might be using outdated version, downloaded the most recent available bin for Linux (0.1.4-alpha) and I can see `MAX` button on `Trade` screen. Is it going to be removed in new release?

![image](https://user-images.githubusercontent.com/15745003/85221868-9fe7bf00-b3e1-11ea-990d-a2c39ddd8796.png)

> Let's say you have 4.777 balance, if you enter 5, it automatically makes that 4.777 minus fees etc.

True, I have not noticed it before.

> Yes, that's what I need, either from you or Slyris. 8 decimals max. Just like I explained above, for 3333333333 value, we need to cut 8 decimals first, so it's 0.33333333, then if the remaining 33333 or 0001 or 111 or 0223 whatever it is, if that part is > 0 then we need to increment the 8th digit by 1 by adding 0.00000001. 0.33333333 will become 0.33333334. That ceiled value will make all comparisons act correctly as I explained at first post. The calculation function is also there.

I'm going to add decimal representation cut to the coins amount of decimals for *displaying* purpose. As I understand you need this to be ceiled? If yes there might be conflict, because I plan to add the volume that will be traded in fact and it will be exactly `0.33333333` for KMD (because KMD has 8 decimals and MM2 just cuts excess digits). According to this test `value: 12345678.12340001    result: 12345678.12340001    expected: 12345678.12340001` it won't be ceiled in GUI code so if you use it as "user input" the condition `input > max` won't hold.

**Comment by naezith** [comment]
> Is it going to be removed in new release?
Yes

> I'm going to add decimal representation cut to the coins amount of decimals for _displaying_ purpose. As I understand you need this to be ceiled? If yes there might be conflict, because I plan to add the volume that will be traded in fact and it will be exactly `0.33333333` for KMD (because KMD has 8 decimals and MM2 just cuts excess digits). According to this test `value: 12345678.12340001 result: 12345678.12340001 expected: 12345678.12340001` it won't be ceiled in GUI code so if you use it as "user input" the condition `input > max` won't hold.

`denom` and `nomer` will be used at `input >= max` condition. Ceiling the `nomer/denom`  result will make sure it works fine at every situation.

**Comment by tonymorony** [comment]
should be implemented now
