### ISSUE TITLE
New transactions doesn't appear in tx history until restart

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#273]
on latest dev if I receive new tx it's not reflecting in tx history (until I restart the app) @naezith  
with such prints in log:

```
qrc:/atomic_qt_design/qml/Wallet/Transactions.qml:28: TypeError: Cannot read property 'width' of null                   qrc:/atomic_qt_design/qml/Wallet/Transactions.qml:28: TypeError: Cannot read property 'width' of null                   qrc:/atomic_qt_design/qml/Wallet/Transactions.qml:28: TypeError: Cannot read property 'width' of null        
```

to reproduce send tx to your atomicdex-pro address and open tab with tx history for that coin

upd: looks like it's not so easily reproducable, got it twice but can't reproduce it now

**Comment by naezith** [comment]
Error is gone with this patch, but I don't know if other problem is still there. https://github.com/KomodoPlatform/atomicDEX-Pro/pull/278
