### ISSUE TITLE
Speed up GHA CI/CD

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#279]
the problem is that builds taking 1hour+ atm.

Easiest way to speedup that (if consider public workers usage) are:

1) GHA actions cache - it works unreliable, flows permanently hangs on loading from cache, also not 100% clear how to detect that new change was added to vpckg repo and we need to rebuild vpckg deps. So I don't think it's solution suitiable for us because we caching non-constant things.

2) Usage of docker containers with all vpckg stuff precompiled inside (probably we can implement it just as special GHA CI for https://github.com/KomodoPlatform/vcpkg which builds needed deps and pushing docker image. That way it'll be easy to update required things. Only concern I have on it is that it might doesn't work on Windows because docker and Windows not friends.

However, all we need is to copy precompiled things from point A ( trusted point) to point B and make point A auto-updatable on our changes.

@SirSevenG do you think option 2 is doable? If you don't have a concerns on that would be great if you go ahead with such thing implementation / usage in current flow.

**Comment by SirSevenG** [comment]
Most build time is wasted on deps, not on actual binary compilation.

1. I do agree, that GHA cache is unreliable and not really transparent on how it works.
Basically, we need to make our own alternative, maybe as point 2 suggests.

2. I can easily see it working on Linux, yet Win and Mac looks sketchy on paper. Generally, I like this idea and will give it a try.
Let's proceed with further discussion after i can personally see(face..?) problems on Win (and, possibly, Mac).

**Comment by Milerius** [comment]
<img width="1343" alt="Capture d’écran 2020-06-22 à 08 48 40" src="https://user-images.githubusercontent.com/21139416/85256890-36a98f80-b465-11ea-9c8d-772476a34311.png">



Managed to reduce linux GA drastically:

<img width="1323" alt="Capture d’écran 2020-06-22 à 08 48 15" src="https://user-images.githubusercontent.com/21139416/85256880-33ae9f00-b465-11ea-8c05-e9df67f98afb.png">

**Comment by Milerius** [comment]
Result now on 0.1.5:

<img width="862" alt="Capture d’écran 2020-06-24 à 12 25 58" src="https://user-images.githubusercontent.com/21139416/85539346-035a3280-b616-11ea-9482-b59e8b6579f6.png">

**Comment by SirSevenG** [comment]
A shoutout to @Milerius on finding  lukka/run-vcpkg actions. Some good stuff, thanks.

lukka/run-vcpkg uses basic cache action [underneath](https://github.com/lukka/run-vcpkg/blob/master/src/vcpkg-action.ts), and cahce action itself was updated to [ver2](https://github.com/actions/cache).
Our main concern initially with cache action was it's a bit unreliable cache (in)validation. Now it seems to be solved, utilising hashfile function.

Regarding GA speed. On top of vcpkg deps, we can cache Qt on Win. You can see in [my fork](https://github.com/SirSevenG/atomicDEX-Pro/runs/816671764?check_suite_focus=true) Win build being done under 15 minutes.

The only concern left is this issue: https://github.com/actions/cache/issues/267

Thus, cache restore can fail or take more time than building. It will not fail the entire build, yet we will have to wait for deps build. And same goes for vcpkg caching. It's a rare occurrence, yet it may happen.

@tonymorony if it's fine with you, I'll prepare PR.

Note on `trusted point`: Milerius implemented our vcpkg fork as github module, and all vcpkg cache is build directly from it. Looks fine for me.

**Comment by tonymorony** [comment]
For now it works at least twice faster then before, so closing this one. Feel free to re-open this one if current speed is still the issue

@SirSevenG also feel free to open PR if you have improvements/another solution which can make current CI/CD harder better faster stronger
