### ISSUE TITLE
Text in fields displaying as hieroglyphs

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#295]
related to https://github.com/KomodoPlatform/atomicDEX-Pro/pull/294 

I'm on windows

![image](https://user-images.githubusercontent.com/24797699/86075880-3f2c4680-bab3-11ea-988f-e753bc46b7da.png)

**Comment by naezith** [comment]
Fixed this recently.

https://github.com/KomodoPlatform/atomicDEX-Pro/commit/37ad734d4ce7a4f80066e3671b15bd447fe92858
https://github.com/KomodoPlatform/atomicDEX-Pro/commit/0bb503ee1d18607f7f83cb4ef59b5afa538d09e3

**Comment by tonymorony** [comment]
this issue was solved on my side
