### ISSUE TITLE
Handling DPI Scaling

### ISSUE THREAD

**Issue by naezith** [KomodoPlatform/atomicDEX-Pro#305]
I did many tests and research, fully understood how everything works.

Currently the UI does not fit to 150% scaling at 1920x1080 monitors. Reason for this is that the app's minimum height is currently 800, and 1.5x of that is 1200. So it's short by 120px, plus there is taskbar and titlebar since application is not fullscreen.

A solution would be to fit everything to 600px height. That way 1.5x will become 900, and 180px for taskbar, titlebar and a bit of extra space.

Since the current version is not properly usable, some buttons are not visible, we should remove `QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);` or turn it to `QCoreApplication::setAttribute(Qt::AA_DisableHighDpiScaling);`. That will make the application run at 1X size even at 150% scaling. The application window and content will be %33 smaller (1 / 1.5), but at least it will be fully functional. It will be small like this, but since our texts are large, it's still readable:

![image](https://user-images.githubusercontent.com/6732486/86272227-e2c24780-bbd6-11ea-99c4-eeda2c538cba.png)

For the new UI, we should keep `QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);`. However Qt, for some reason, by default, uses scaling policy as `Round`. That means 150% or 1.5X scaling rounds up to 2X, 200%. This is incredibly bad because it gets bigger than it should. Like here:

![image](https://user-images.githubusercontent.com/6732486/86272075-ad1d5e80-bbd6-11ea-8cf7-941ef68c359f.png)

Adding `QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);` line makes 150% work as 150%, like it should be. It's unbelievable that this is not the default policy. With that, it becomes true 150% like this, but it still does not fit since 1.5x is 1200: 

![image](https://user-images.githubusercontent.com/6732486/86272407-30d74b00-bbd7-11ea-9a9f-a5f14f7acd25.png)

We always see people reporting this issue on Windows, because if you use an external 1920x1080 monitor using macOS, you don't have an option to have 150% scaling as shown here:

![image](https://user-images.githubusercontent.com/6732486/86271791-31231680-bbd6-11ea-8dd2-80b4784ff558.png)

So you can't have 150% 1080p problem with an external monitor on macOS. And the MacBook users, let's say 13 inch, have 2560 x 1600 vast screen real estate. Scaling is 150% so 800px height becomes 1200, and that easily fits to 1600px screen. 

These are all technical but the "real" issue is that there are many laptops with 1080p resolution squeezed into 13 inch, and at Windows 150% is recommended for that. It's a really really small area, 1280x720, plus taskbar + titlebar, apps need to fit to something like 600px, designers should keep that in mind. 

By 600px, I talk about 600px at a classic 96 DPI.

I hope this post clears everything.

**Comment by tonymorony** [comment]
looks fine in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/403

tested on `13" 1920x1080 175% zoom`
