### ISSUE TITLE
[BUG] allow GUI to start with VPN on every OS

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#308]
Mobile app works with VPN, however desktop app doesn't start - its good to test/isolate that to at least know the reason

**Comment by tonymorony** [comment]
@SirSevenG plesase help with research of this one to isolate the reason why GUI not start with enabled VPN

**Comment by Milerius** [comment]
@naezith Please provide the small snippet of code that you are using to know if you have a valid connection in QML

**Comment by naezith** [comment]
> @naezith Please provide the small snippet of code that you are using to know if you have a valid connection in QML

https://github.com/KomodoPlatform/atomicDEX-Pro/blob/naezith_dev/atomic_qt_design/qml/NoConnection.qml

It's very primitively pinging Google.

**Comment by SirSevenG** [comment]
So far tested on Linux(Ubuntu bionic) and Win10.

On Ubuntu app starts fine with vpn on/off, reconnects without issues when turning vpn on/off while app is running.

On WIn10, when vpn is on, application fails to start, showing `No Connection` scene.
Debug terminal output:
https://paste.ubuntu.com/p/XcrfNgRmxr/
Log:
https://paste.ubuntu.com/p/7c4KNGBGf8/

When app is running, if you turn vpn on, `No Connection` scene will be shown indefinitely.
To access app after, you need to shut it down, turn off vpn and start AtomicDEX anew.
Yet, mm2.exe process will reconnect and remain active in the background fetching orderbooks and running swaps.
AE: while swap is ongoing, enabling vpn connection will not fail the swap, it will just effectively disable GUI.
Log example:
https://paste.ubuntu.com/p/79mPt5Qfrw/

From logs/debug terminal exact issue is unclear.

**Comment by naezith** [comment]
Can you try a basic "ping google.com" in Windows's CMD when `No Connection` is present. @SirSevenG

**Comment by SirSevenG** [comment]
Ping itself works fine.
```powershell
PS E:\> ping google.com

Обмен пакетами с google.com [172.217.21.174] с 32 байтами данных:
Ответ от 172.217.21.174: число байт=32 время=75мс TTL=119
Ответ от 172.217.21.174: число байт=32 время=78мс TTL=119
Ответ от 172.217.21.174: число байт=32 время=76мс TTL=119
Ответ от 172.217.21.174: число байт=32 время=74мс TTL=119

Статистика Ping для 172.217.21.174:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 74мсек, Максимальное = 78 мсек, Среднее = 75 мсек
PS E:\> ping coinpaprika.com

Обмен пакетами с coinpaprika.com [104.22.25.108] с 32 байтами данных:
Ответ от 104.22.25.108: число байт=32 время=75мс TTL=59
Ответ от 104.22.25.108: число байт=32 время=73мс TTL=59
Ответ от 104.22.25.108: число байт=32 время=75мс TTL=59
Ответ от 104.22.25.108: число байт=32 время=74мс TTL=59

Статистика Ping для 104.22.25.108:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 73мсек, Максимальное = 75 мсек, Среднее = 74 мсек
```

![изображение](https://user-images.githubusercontent.com/44422309/86518429-43ae8180-be5c-11ea-9c49-45139feb3b53.png)

**Comment by naezith** [comment]
Then my guess is that `doc.readyState` is having different values, I'll check in future.

**Comment by SirSevenG** [comment]
If there is a way to dump `doc.readyState` value in terminal/log to check, it might be helpful.

**Comment by naezith** [comment]
@SirSevenG I am working on something else but you can simply add `console.log(doc.readyState)` before this if statement and compile. https://github.com/KomodoPlatform/atomicDEX-Pro/blob/naezith_dev/atomic_qt_design/qml/NoConnection.qml#L26

**Comment by SirSevenG** [comment]
Win10 with vpn:
```
qml: 1
qml: 4
qml: 1
qml: 4
qml: 1
qml: 4
```
Skips '2' and '3' states.

On Linux with vpn, for comparison:
```
qml: 1
qml: 2
qml: 3
qml: 3
...
qml: 3
qml: 4
```

**Comment by naezith** [comment]
I figured out the problem but it's too messy to handle it at QML side. So @Milerius will handle this online status at the backend.

**Comment by tonymorony** [comment]
Connection detection part should be improved by https://github.com/KomodoPlatform/atomicDEX-Pro/pull/399
