### ISSUE TITLE
[FEATURE REQUEST]: Address book

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Pro#312]
**Is your feature request related to a problem? Please describe.**

The feature is not linked to a problem but to a lack.
We have no way of registering a public address for a name.

**Describe the solution you'd like**

I would like to be able to associate a public address with a name, this name could be associated with all a group like "ERC-20" or "SmartChains". 

Later we could add categories: **Friends**, **Professional**, **Contractual**

**Describe alternatives you've considered**

Currently I use an external tool to which I associate an address to a name, but I therefore need to copy my public address from the application and then perform the search in my tool. It is laborious.

**Additional context**

- Send / Withdraw feature are concerned.

A Json attempt of the addressbook format added to the wallet configuration:

```json
{
    "wallet_name": "roman",
    "addressbook": {
        "ca333": {
            "ERC-20": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "SmartChains": "RB49Rm4jBe5mN9anErvkzf3kcQCzHqyz3e",
            "BTC": "3FZbgi29cpjq2GjdwV8eyHuJJnkLtktZc5"
        },
        "alice": {
            "ERC-20": "0xde0b395669a9fd93d5f28d9ec85e40f4cb697bae",
            "SmartChains": "RB39Rm4jBe5mN9anErvkzf3kcQCzHqyz3e",
            "BTC": "3FZbgi30cpjq2GjdwV8eyHuJJnkLtktZc5"
        },
        "bob": {
            "ERC-20": "0xde0b393669a9fd93d5f28d9ec85e40f4cb697bae",
            "SmartChains": "RB39Rm6jBe5mN9anErvkzf3kcQCzHqyz3e",
            "BTC": "3FZbgi30cpjq3GjdwV8eyHuJJnkLtktZc5"
        }
    },
    "categories": {
        "friends": [
            "ca333"
        ],
        "pro": [
            "alice"
        ],
        "black_list": [
            "bob"
        ]
    }
}
```

**Comment by tonymorony** [comment]
![Address Book Desktop Concept](https://user-images.githubusercontent.com/24797699/87242846-c2a64a00-c45a-11ea-9b0a-413c613dd584.png)

I think there might be dropdown scrollable list linked with addressbook when you input recepient (probably Audo can make it beautiful):

![image](https://user-images.githubusercontent.com/24797699/87242919-5c6df700-c45b-11ea-9552-5bfaa9af7de9.png)

Also I've noticed that there is a lot of free space at the moment. I think it's fine to put addressbook button here for now (between receive and swap):

![image](https://user-images.githubusercontent.com/24797699/87242939-89baa500-c45b-11ea-956f-4a2f918dbce0.png)

**Comment by tonymorony** [comment]
impleneted in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/357
