### ISSUE TITLE
[BUG]: Candlesticks chart not clearing after you change a pair

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#319]
**Describe the bug**
Candlesticks chart not clearing after you change a pair. I propose to not display this widget at all when user select pair without price information.

**To Reproduce**
1. Select KMD/BTC - chart will be drawn
2. Select some different pair e.g. KMD/DEX
3. There still be chart for KMD/BTC

**Expected behavior**
Clear chart

**Screenshots**
![image](https://user-images.githubusercontent.com/24797699/86529164-9fb6eb80-bed8-11ea-8fd7-a1365a219831.png)

**Comment by naezith** [comment]
Fixed by https://github.com/KomodoPlatform/atomicDEX-Pro/pull/334

**Comment by tonymorony** [comment]
candles clearing now but averages are still on the graph:

![image](https://user-images.githubusercontent.com/24797699/86562489-fa118400-bf8c-11ea-9097-45c990a5a85c.png)

**Comment by tonymorony** [comment]
lgtm, thanks
