### ISSUE TITLE
[Enhancement]: Scroll not limiting element border in some cases

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#324]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/24797699/86529715-2241aa00-bedd-11ea-978a-48c2f25484e3.png)

![image](https://user-images.githubusercontent.com/24797699/86529733-3edde200-bedd-11ea-84d2-a9b2007d39bf.png)

![image](https://user-images.githubusercontent.com/24797699/86532847-1f53b300-bef7-11ea-8ebe-7cf89a90e6c1.png)

**Describe the solution you'd like**
I think that scroll should limit edge of the element

**Comment by naezith** [comment]
https://github.com/KomodoPlatform/atomicDEX-Pro/commit/2d125f2589b137f8a4c01ba15318292a7f578950
