### ISSUE TITLE
[BUG/Enhancement]: Not enough precision in USD price indication

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#325]
**Describe the bug**

Doge price is less than 1 cent so it's indicating as 0 because we use two decimal places. When price per single coin is not huge decimal places is very critical, lets say DGB indicating as 0.02 but difference between 0.02 and 0.0299 actually is 50%

I propose to increase amount of decimal places for USD price indication in all parts of the application.

![image](https://user-images.githubusercontent.com/24797699/86529840-2f12cd80-bede-11ea-8af0-eb01ec249e9c.png)

![image](https://user-images.githubusercontent.com/24797699/86529850-48b41500-bede-11ea-906d-e9bb1c0195ba.png)

**Comment by Milerius** [comment]
Fixed by #317

**Comment by tonymorony** [comment]
Price for DOGE is >0 now but I don't think it's globally fixed (see `lets say DGB indicating as 0.02 but difference between 0.02 and 0.0299 actually is 50%`) , lets not hurry and think how to keep needed precision

![image](https://user-images.githubusercontent.com/24797699/86570163-b5401a00-bf99-11ea-9410-eab276e1b664.png)

**Comment by naezith** [comment]
Back-end related, as front-end does not touch to these values.

**Comment by tonymorony** [comment]
Price looks fine now for me, great! 

but we got undefined for Wallet balance atm [ CC @naezith ] : 

![image](https://user-images.githubusercontent.com/24797699/87151259-b779df80-c2dd-11ea-9610-fcf651bc740a.png)

**Comment by naezith** [comment]
That's fixed.

**Comment by tonymorony** [comment]
Looks good now. Thanks!
