### ISSUE TITLE
EnTT CMake Error on Build

### ISSUE THREAD

**Issue by csharpee** [KomodoPlatform/atomicDEX-Pro#33]
After running ./ci_tools_atomic_dex build debug

```
CMake Error at ci_tools_atomic_dex/vcpkg-repo/scripts/buildsystems/vcpkg.cmake:286 (_find_package):
  Could not find a package configuration file provided by "EnTT" with any of
  the following names:

    EnTTConfig.cmake
    entt-config.cmake
```

Further research https://github.com/skypjack/entt/issues/451 shows a similar issue being worked on about 8hrs ago.

**Comment by Milerius** [comment]
#36 should solved the problem, if the problem persist please let me know !
