### ISSUE TITLE
[FEATURE REQUEST]: Switch/toggle currency (Fiat/KMD/BTC)

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#331]
**Is your feature request related to a problem? Please describe.**

It'll help to evaluate assets value not in fiat only

**Describe the solution you'd like**
Tri-toggle like a https://blog.blockfolio.com/ether-you-get-it-or-you-dont-blockfolio-s-next-major-update-1-1-11-is-here-5f1ce5a49f77

**Comment by Milerius** [comment]
Just look at the appdata toggle switch @naezith

**Comment by tonymorony** [comment]
besides of portfolio selected currency should be reflected in these calculations: https://github.com/KomodoPlatform/atomicDEX-Pro/issues/326

**Comment by tonymorony** [comment]
cf: https://github.com/KomodoPlatform/atomicDEX-Pro/issues/345

**Comment by tonymorony** [comment]
implemented in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/344
