### ISSUE TITLE
[Enhancement]: Missing paddings between elements on popups

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#333]
On screenshots all places caught my eye, probably it's possible to standartize it trough whole app some oop way in future.
I'm not sure if we should do it right now, but might be good to keep in mind if/when we'll have more designs for various elements.

![image](https://user-images.githubusercontent.com/24797699/86531240-bade2700-bee9-11ea-9ba0-dc08e2864b90.png)
![image](https://user-images.githubusercontent.com/24797699/86531247-c5002580-bee9-11ea-9878-f307098a886d.png)
![image](https://user-images.githubusercontent.com/24797699/86531255-dd704000-bee9-11ea-892a-0527afaa380b.png)
![image](https://user-images.githubusercontent.com/24797699/86531262-ea8d2f00-bee9-11ea-8333-ea4353dbf9a2.png)
![image](https://user-images.githubusercontent.com/24797699/86531279-fd9fff00-bee9-11ea-9df1-efcc9a9e0dae.png)

**Comment by naezith** [comment]
Made generic Modal components which also supports multiple pages. All modals use them now. Their margins are adjusted globally. This should be solved now in #460
