### ISSUE TITLE
[BUG]: Tx fee for erc displaying in ERC instead of ETH

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#339]
**Describe the bug**
Tx fee for erc displaying in ERC instead of ETH

**Expected behavior**
Tx fee in ETH

**Screenshots**
![image](https://user-images.githubusercontent.com/24797699/86594151-b46eae80-bfc0-11ea-9136-d325f0ab1213.png)
![image](https://user-images.githubusercontent.com/24797699/86594172-bcc6e980-bfc0-11ea-8089-4dcbb28ea03f.png)

**Comment by Milerius** [comment]
I thin for this @naezith you can just check coin type if it's erc-20

**Comment by tonymorony** [comment]
fixed in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/363
