### ISSUE TITLE
[Enhancement]: display 1hr scale chart by default instead of 1m

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#347]
by default 1m scale chart displaying at the moment, however 1h chart is more informative/useful (and more beautiful, hehe) 

1 minute chart:
![image](https://user-images.githubusercontent.com/24797699/87023252-a8bdfa80-c201-11ea-9cf2-c0c45c76111b.png)

1 hour chart:
![image](https://user-images.githubusercontent.com/24797699/87023278-b1163580-c201-11ea-866a-1c7d82a14d58.png)

**Comment by tonymorony** [comment]
P.S. what does these zeroes mean? 

![image](https://user-images.githubusercontent.com/24797699/87023738-5d581c00-c202-11ea-808e-29d46d97ebe4.png)

**Comment by naezith** [comment]
Hmm, they broke somehow. I'll check that.

**Comment by tonymorony** [comment]
I wonder that trades happening not every minute for that pair thats why there are gaps
