### ISSUE TITLE
Potential problems when building on Windows 

### ISSUE THREAD

**Issue by naezith** [KomodoPlatform/atomicDEX-Pro#35]
I was following the building instructions for Windows. 

I had Visual Studio 2019 installed before but `Desktop development with C++` was not selected. And I was not aware.

A tiny problem was this:
```cmd
D:\Projects\atomicDEX-Pro\atomic_qt\ci_tools_atomic_dex>./ci_tools_atomic_dex.exe build release
'.' is not recognized as an internal or external command,
operable program or batch file.
```

After running it, for first time, I got this error:
![image](https://user-images.githubusercontent.com/6732486/77776513-2b5de800-705f-11ea-9a1b-010e7fde7d8f.png)

Then it took a while to figure out that it's because `Desktop development with C++` was not installed. I installed that.

At my next try, it failed like this:

```
D:\Projects\atomicDEX-Pro\atomic_qt\ci_tools_atomic_dex>ci_tools_atomic_dex.exe build release
D:\Projects\atomicDEX-Pro\atomic_qt\ci_tools_atomic_dex\vcpkg-repo\vcpkg
D:\Projects\atomicDEX-Pro\atomic_qt\ci_tools_atomic_dex\vcpkg-repo\scripts\buildsystems\vcpkg.cmake
Downloading packages ... please wait
D:\Projects\atomicDEX-Pro\atomic_qt\ci_tools_atomic_dex\src\ci_tools_atomic_dex.nim(52) ci_tools_atomic_dex
D:\Projects\atomicDEX-Pro\atomic_qt\ci_tools_atomic_dex\src\ci_tools_atomic_dex.nim(42) main
D:\Projects\atomicDEX-Pro\atomic_qt\ci_tools_atomic_dex\src\build.nim(7) build_atomic_qt
D:\Projects\atomicDEX-Pro\atomic_qt\ci_tools_atomic_dex\src\generate.nim(12) generate_solution
D:\Projects\atomicDEX-Pro\atomic_qt\ci_tools_atomic_dex\src\dependencies.nim(21) download_packages
C:\ProgramData\scoop\apps\nim\current\lib\pure\osproc.nim(750) execCmd
C:\ProgramData\scoop\apps\nim\current\lib\pure\includes\oserr.nim(94) raiseOSError
Error: unhandled exception: The system cannot find the file specified.
 [OSError]

D:\Projects\atomicDEX-Pro\atomic_qt\ci_tools_atomic_dex>
```

When I saw `nim` complaining, I remembered that after `scoop install nim --global`, my antivirus BitDefender removed a file inside that, and I restored that file. But I had no other clue so I thought this is because of that BitDefender issue. I added exceptions, tried many many different stuff to reinstall nim, but it was always being stuck at `Extracting nim...`. It installed fine when I removed `--global`.

I thought it will work at this point but when I tried, I got exactly the same error. Then I digged into  
`dependencies.nim` and `vcpkg.nim` and found these two parts:

```nim
proc check_if_vcpkg_exists*(): bool =
    result = os.existsDir("vcpkg-repo")

proc install_vcpkg*() =
    set_vcpkg_path()
    if not check_if_vcpkg_exists():
        echo "Installing vcpkg"
        discard execCmd("git clone https://github.com/microsoft/vcpkg vcpkg-repo")
        build_vcpkg()
        integrate_vcpkg()
    else:
        echo "vcpkg repo exist"
        build_vcpkg()
        integrate_vcpkg()
```

After seeing that `check_if_vcpkg_exists` function, I deleted `vcpkg-repo` folder. And the build started running this time.

Yes, all of this chain of problems is caused by `Desktop development with C++` not being installed.

I thought this time it will run perfectly but after a really long build, it failed.
Here is the log: https://paste.ubuntu.com/p/tnqqYM92PN/

EnTT problem continues here: https://github.com/KomodoPlatform/atomicDEX-Pro/pull/36#issuecomment-605113046

**Comment by tonymorony** [comment]
@naezith Is it still actual? I believe that building works fine now on Windows because I can build it fine on my PC and @Milerius made some windows-specific changes in building tools

**Comment by naezith** [comment]
This is really out-dated and my environment is not fresh so I can't test.

**Comment by tonymorony** [comment]
thanks for update, closing this one
