### ISSUE TITLE
[BUG]: Swaps history break

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#350]
**Describe the bug**

I've used the app quite actively and performed over than 30 swaps as maker and taker, on some point my "Recent swaps" page cleared and new swaps not displaying here however DB is still there. I suspect that some swap file broke it, investigating.

App version: latest dev, OS: Windows

Log: [history_adex.log](https://github.com/KomodoPlatform/atomicDEX-Pro/files/4901610/history_adex.log)

Noticed adex-api panic in log, maybe it's related:

```
10 07:08:23, common:438] panicked at '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!   unwrap! called on Result::Err                                              !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
mm2src\coins\lp_coins.rs:397,9 in coins

Err(Os { code: 87, kind: Other, message: "The parameter is set incorrectly." })

', <::std::macros::panic macros>:5:6
10 07:08:23, common:439] backtrace
  ??:0] BaseThreadInitThunk 0x7ffbecf97bd3
  ??:0] RtlUserThreadStart 0x7ffbedd2ce50
```

**Comment by tonymorony** [comment]
By bisection method I've found a file caused it:


[6462abf3-bcb9-46dc-bd55-693361d147e4.zip](https://github.com/KomodoPlatform/atomicDEX-Pro/files/4901645/6462abf3-bcb9-46dc-bd55-693361d147e4.zip)

**Comment by tonymorony** [comment]
that looks like exactly the same problem as in https://github.com/KomodoPlatform/atomicDEX-Pro/issues/234 so it's not fixed it seems

**Comment by artemii235** [comment]
@tonymorony Do you see the panic repeatedly or it happened just once? It was caused by this code https://github.com/KomodoPlatform/atomicDEX-API/blob/08d013c6a5983ccb590b246a5600387f9918a805/mm2src/coins/lp_coins.rs#L397, history cache file failed to be renamed and panicked due to unwrap, we should handle this gracefully on MM2 side. Could you please open an issue in AtomicDEX-API repo for further investigation?

**Comment by tonymorony** [comment]
@artemii235 I can see it on every GUI startup, sure will open the issue now

**Comment by Milerius** [comment]
I'm following this one, thanks for the issue @tonymorony

**Comment by tonymorony** [comment]
> I'm following this one, thanks for the issue @tonymorony

great! yea, would be superb if GUI can handle "type": "StartFailed" swaps

**Comment by tonymorony** [comment]
fixed in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/349
