### ISSUE TITLE
[BUG]: View In Explorer URL incorrect

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Pro#381]
When clicking the "View at explorer" button on a ZEC transaction, it goes to a URL like 

https://explorer.zcha.in/tx/18b5f463cfd4ebf9a27d3149877007c8444107f88775ce7c6840eb545616f777
which is 404

Correct URL should be 
https://explorer.zcha.in/transactions/18b5f463cfd4ebf9a27d3149877007c8444107f88775ce7c6840eb545616f777

**To Reproduce**
1. Go to Wallet tab and select ZEC
2. Click on a transaction, then on "View at explorer"

**Expected behavior**
Expected link to show transaction details on explorer, but due to URL path having `tx` instead of `transactions` there is a 404 error: page not found

**Comment by tonymorony** [comment]
@smk762 could you please check if it's the case for any another coin we have in adex-pro?

**Comment by smk762** [comment]
I'll check those I have funds for, and make a list of the others to check once funds are available (or if someone else has funds for those to check)

**Comment by smk762** [comment]
Found a few more:

EMC2 (bad path) - use https://chainz.cryptoid.info/emc2/tx.dws?
CHIPS (timeout - no SSL) - use http://explorer.chips.cash/tx
DASH (502 error) - use https://blockchair.com/dash/transaction
ILN (502 error) - use https://iln.explorer.dexstats.info/

Coins not yet tested (I don't have balance):
AWC, BUSD, DAI, ECA, FTC, JUMBLER, NAV, PAX, TUSD, USDC, XZCm ZER

**Comment by naezith** [comment]
I am constructing the URL manually like this `coin_info.explorer_url + 'tx/' + ...`. Similarly there is `coin_info.explorer_url + 'address/' + ...` use too. My suggestion is to have `explorer_tx_url` and `explorer_address_url` which will include the URI part. @Milerius

**Comment by tonymorony** [comment]
should be fine now
