### ISSUE TITLE
[FEATURE REQUEST]: Visual market depth in orderbook table

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#390]
way of implementation might be similar to binance: summarize depth of orders and then draw horizontal bars based on orders depths relation

![image](https://user-images.githubusercontent.com/24797699/88613106-f4541d80-d0b6-11ea-9afc-44d6ec9f97fd.png)

**Comment by tonymorony** [comment]
this one I think we should combine with adding a possibility to see orders/orderbook even if user has 0 balance - that was most wanted feature for mobile GUI :)

(after order select just show text message on bottom like a "insufficient balance for ordermatching")

**Comment by naezith** [comment]
Can you clearly explain how exactly each line is calculated?

**Comment by tonymorony** [comment]
> Can you clearly explain how exactly each line is calculated?

summarize depth of visible orders, then `precentage_of_line_filling = (dept_of_particular_visible_order /  total_depth) * 100`, then `line_length = widget_max_width  * precentage_of_line_filling`
