### ISSUE TITLE
[BUG]: API fails to fetch my_orders and display them when no timezone is found on user system

### ISSUE THREAD

**Issue by imylomylo** [KomodoPlatform/atomicDEX-Pro#392]
**Description**

```
[08:50:31 +00:00] [E] [thr 20192] rpc_process_answer l878 f[atomic.dex.mm2.api.cpp], exception caught Could not get current timezone for rpc my_orders
```
GUI does not display my orders even though it is broadcast and viewable through external orderbook view.

**To Reproduce**

Have no `/etc/localtime` symlink (like my system), however timedatectl status responds with my system time (UTC)
```
$ timedatectl status
               Local time: Tue 2020-07-28 09:17:40 UTC
           Universal time: Tue 2020-07-28 09:17:40 UTC
                 RTC time: Tue 2020-07-28 09:17:40    
                Time zone: UTC (UTC, +0000)           
System clock synchronized: yes                        
              NTP service: active                     
          RTC in local TZ: no 
```
Place an order, watch for the `[08:50:31 +00:00] [E] [thr 20192] rpc_process_answer l878 f[atomic.dex.mm2.api.cpp], exception caught Could not get current timezone for rpc my_orders` exception in the console.

GUI will not update with order info, because it was not returned from middleware.

**Expected behavior**
Orders viewable.

**Desktop (please complete the following information):**
ArchLinux, using 0.2.0-alpha download for linux.

**Additional context**
Discord chat: https://discord.com/channels/412898016371015680/705374203972419616/737592769136164874

**Comment by tonymorony** [comment]
should be fixed by https://github.com/KomodoPlatform/atomicDEX-Pro/pull/401 

tested with totally doomed local timezone settings:
![image](https://user-images.githubusercontent.com/24797699/89250062-0fd2a180-d63e-11ea-995c-12207b1eac5b.png)

thanks for this issue opening!
