### ISSUE TITLE
[FEATURE REQUEST]: Confirmation requirements in settings (custom dPoW configs)

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#405]
crf and helpful info: https://github.com/ca333/komodoDEX/issues/690

such params were added into `buy/sell/setprice` calls:

![image](https://user-images.githubusercontent.com/24797699/89192105-17f2f880-d5ce-11ea-816f-f0dd4d00f543.png)

what allows us to buypass default values set in `coins` file for every particular trade. I think would be great to collaborate with @yurii-khi on this one to make same UI style/logic of work on both desktop and mobile platfroms.

**Comment by Milerius** [comment]
In c++ we have `std::optional` I will simply use that from my side, I will share pseudo code later

**Comment by tonymorony** [comment]
Please note that custom conf/nota rules is possible to set only for incoming txs:

For `sell` calls: user receive rel and send base - so need confirmations settings for rel coin
For `buy` calls: user receive base coin and send rel - confs settings for base
For `setprice` calls: user receive rel and send base - confs settings for rel

**Comment by tonymorony** [comment]
also I think it worth to mention that dPoW protection enabling/disabling (waiting for notarisation) might be the case only for incoming `ACs with dPoW, KMD and dPoWed "3P coins"` transactions (otherwords for assets which have dPoW protection in general)

refs:

https://github.com/KomodoPlatform/coins/blob/master/coins
coins with `"requires_notarization": true`

https://github.com/KomodoPlatform/dPoW#dpow-asset-status

**Comment by tonymorony** [comment]
implemented in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/415 and https://github.com/KomodoPlatform/atomicDEX-Pro/pull/412
