### ISSUE TITLE
[BUG]: DEX page state auto-resets to BTC-KMD in some time 

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#413]
time to time selectors on DEX page switching to BTC-KMD during interaction with app

![image](https://user-images.githubusercontent.com/24797699/89408737-084cee80-d74b-11ea-82e4-a5b82480cf7f.png)

**Comment by naezith** [comment]
It's ticker ComboBox'es resetting I think, because the balance text changes, it resets, just like lists were resetting the scroll. So for this we would like to have a model I think. @Milerius

**Comment by tonymorony** [comment]
1)

![image](https://user-images.githubusercontent.com/24797699/89726869-d6d56b00-da49-11ea-9abe-aa1efd147612.png)


To reproduce select order for pair where one ticker got usd price and another not and then flip it by arrows button.
then the'll be random stuff on this "Expedient/Expensive" widget on order select

2)

![image](https://user-images.githubusercontent.com/24797699/89726886-084e3680-da4a-11ea-85be-05a027588400.png)

if `required_confirmations` field is not set in coins file just print 1 confirmation - thats how mm2 behave atm

**Comment by tonymorony** [comment]
fixed in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/415, thanks!
