### ISSUE TITLE
[BUG]: Dashboard list redacted when disabling coin and order matches a second later

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Pro#436]
If attempting to disable coin(s) which have an unmatched swap pending, and the swap matches around the same time, it can leave the GUI in a state where:
- coins are still enabled (and order progresses)
- coins no longer displayed on Dashboard
- coins still visible on Wallet page
- coins not visible in "Enable coins" list

**Steps to reproduce** 
1. Place taker order
2. Quickly disable coin(s) from wallet page
3. View Dashboard / DEX / Enable Coin pages

**Expected behavior**
Either orders are cancelled (perhaps giving user msgbox to warn coin has pending orders and confirm cancelling before disable) then coin disabled, or ensure Dashboard & Wallet pages retain listing of coins which are actively in swap.

**Screenshots**
Video of process and outcome in zip
[coin_disable.zip](https://github.com/KomodoPlatform/atomicDEX-Pro/files/5096291/coin_disable.zip)

**Desktop**
 - OS: Ubuntu 18.04
 - Version 0.2.1

**Comment by tonymorony** [comment]
re-tested, shouldn't be possible atm so closing this one
