### ISSUE TITLE
[FEATURE REQUEST]: Add your own ERC20 Tokens

### ISSUE THREAD

**Issue by theblackmallard** [KomodoPlatform/atomicDEX-Pro#442]
Add ability to load custom ERC20 tokens by contract address. Images may need to be a default ERC20 image unless we can pull the image from somewhere else, or add more to the coin.conf file

**Comment by tonymorony** [comment]
thanks for the issue opening! 

thats one of the features we consider for beta/post-beta roadmap

**Comment by tonymorony** [comment]
implemented in https://github.com/KomodoPlatform/atomicDEX-Pro/pull/476
will be availiable in 0.3.0 release
