### ISSUE TITLE
[BUG]: Improve the visibility of the 'Sell' button label when in dimmed state (when Buy is selected)

### ISSUE THREAD

**Issue by jansako** [KomodoPlatform/atomicDEX-Pro#455]
**Describe the bug**
Currently it is quite hard to see/read the label on the 'Sell' button when in 'dimmed' state (when the 'Buy' is selected). 

**To Reproduce**
Trade tab, to right corner :-).

**Expected behavior**
The 'dimmed' state of the 'Sell' button should be a bit lighter. The highlighted state matches the Magenta of the sell order book which is great, and the 'dimmed' magenta color is not used anywhere else so it would not break the scheme...

**Screenshots**
![image](https://user-images.githubusercontent.com/34211887/91699830-bb7ded00-eb29-11ea-8901-842a9607b9b9.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Version 0.21

**Comment by naezith** [comment]
https://github.com/KomodoPlatform/atomicDEX-Pro/commit/004f908f21737b9a440f3d757d50279c45aab728

**Comment by tonymorony** [comment]
should be more visible now and it became bright when user's mouse on it :) 

![image](https://user-images.githubusercontent.com/24797699/93737119-85092e80-fc0c-11ea-9d04-c0fb7b64ed0d.png)
