### ISSUE TITLE
Able to load tx history from previously clicked coin

### ISSUE THREAD

**Issue by dathbezumniy** [KomodoPlatform/atomicDEX-Pro#462]
When you switch coins very fast on the wallet page it is possible ~~to become a billionaire~~ to load the tx history from a previously clicked coin.

Here's a video on how to reproduce:
https://drive.google.com/file/d/1BXJJByVoK4qTTgX5M50THwtInIwYsxqN/view?usp=sharing

MacOS 10.15.6 on stylized_combobox branch

**Comment by naezith** [comment]
Please try https://github.com/KomodoPlatform/atomicDEX-Pro/commit/5c328aaa150c99d9168faaadc5307af2c77f1234

**Comment by tonymorony** [comment]
Seems to be fixed now, thanks
