### ISSUE TITLE
[BUG]: max_send does not display the right amount for qrc20

### ISSUE THREAD

**Issue by dathbezumniy** [KomodoPlatform/atomicDEX-Pro#464]
max_send does not display the right amount on both prepare-tx and tx-complete screen.
<img width="662" alt="Screenshot 2020-09-17 at 19 02 38" src="https://user-images.githubusercontent.com/11756768/93468675-893a0100-f919-11ea-8d67-385dc0cc06fc.png">
<img width="654" alt="Screenshot 2020-09-17 at 19 02 48" src="https://user-images.githubusercontent.com/11756768/93468682-8b03c480-f919-11ea-8530-ac26ab406841.png">
<img width="664" alt="Screenshot 2020-09-17 at 19 02 59" src="https://user-images.githubusercontent.com/11756768/93468687-8ccd8800-f919-11ea-9031-6b6ab6e3112f.png">

macos 10.15.6 on stylized_combobox branch

**Comment by tonymorony** [comment]
That problem was resolved on adex API side https://github.com/KomodoPlatform/atomicDEX-API/pull/727 so API version bump should resolve that CC [ @Milerius ]

**Comment by tonymorony** [comment]
fixed by https://github.com/KomodoPlatform/atomicDEX-Pro/pull/476/commits/94a5dc790b6cb7933e21e06e3911d89613f0d7bb
