### ISSUE TITLE
[BUG]: Balance on selectors not updating automatically

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#469]
**Describe the bug**

Lets say you have KMD on one of the selectors. After you send or receive KMD, KMD balance on selector will change only after you change selection to some another coin and back to KMD.

**To Reproduce**
1. Go to DEX
2. Select coins on selectors
3. Perform tx for one of the selected coins
4. Check balance on selector for this coin

**Expected behavior**
Automatical update of balance on selectors after balance change

**Screenshots**
![image](https://user-images.githubusercontent.com/24797699/93713762-47fb5880-fb88-11ea-8946-221de5c4bab4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version `stylized_combobox`

**Comment by naezith** [comment]
Balance is updated from backend, probably a backend task @Milerius

**Comment by tonymorony** [comment]
looks fine now, thanks
