### ISSUE TITLE
[BUG]: Invisible toaster after maker order creation

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Pro#475]
**Describe the bug**
After maker order creation there is invisible toaster on the bottom of orderbook section which opening order creation log on click.

**To Reproduce**
Video shared in kb

**Comment by naezith** [comment]
https://github.com/KomodoPlatform/atomicDEX-Pro/commit/5b99b51f0285ab4b12bbd694d4f5ded21b0da16f
