### ISSUE TITLE
wrong format for balance

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Pro#98]
![adex](https://user-images.githubusercontent.com/32116761/79269273-b32f5900-7e8b-11ea-9b97-b9386ffeb87d.png)
balance on trade tab is showed in wrong format when balance is low

**Comment by tonymorony** [comment]
Thanks for the issue reporting! 
Now it's not possible to access that field at all with balance less than 0.00777 so that issue should be not actual :) Feel free to re-open if its not the case
